### ISSUE TITLE
how to use billing volume and s3

### ISSUE THREAD

**Issue by fireba11** [fi-ts/cloudctl#147]
Our contract got billing for s3 and volumes as GB/months.
billing volume/s3 expects GB/hour
How to properly convert that so we arrive at the same numbers? :-)

**Comment by Gerrit91** [comment]
Hey. I'm afraid that as a developer I don't know about contracts and final numbers of a bill.

When you look into the response of the billing command, you see that the API returns storage seconds:

```
$ c billing s3 -o yaml
...
    - bucketid: ...
      bucketname: test-92
      currentnumberofobjects: "33183"
      currentsize: "16827887616"
      end: null
      lifetime: 1352690064000000
      partition: fel-wps101
      projectid: ...
      projectname: ""
      start: "1970-01-01T00:00:00.000Z"
      storageseconds: "22762916224820859"
      tenant: ...
      user: ...
      warnings: []
```

This number is seconds * bytes, so you can convert this from byte to GB: 22762916224820859 / 2³⁰ = 21199617,7443 s * GB

Then convert to hours: 21199617,7443 s * GB / 3600 = 5888,78270675 GB * h

This is what cloudctl does in the table view and it is the value we hand down to the billing department for the creation of the bills. It can be that some products include a minimum purchase or other multiplication factors though. Maybe then there are better persons to ask for how the final numbers are made.

**Comment by fireba11** [comment]
thanks
