### ISSUE TITLE
volumes show usage 0B

### ISSUE THREAD

**Issue by fireba11** [fi-ts/cloudctl#166]
cloudctl volume ls
always shows usage as 0B

**Comment by fireba11** [comment]
and this clearly can't be correct either ;-)

cloudctl volume ls -o json
[...]
        "Size": 322122547200,
        "State": "Available",
        "Statistics": {
            "CompressionRatio": 0,
            "LogicalUsedStorage": 0,
            "PhysicalUsedStorage": 268415473856
        },

**Comment by majst01** [comment]
Hi @fireba11,

Thanks for the BUG report, to nail down your problem, can you please give me the volume uuid (first column), thanks

**Comment by fireba11** [comment]
Example: 3954a77f-1ceb-4acc-80b8-f00807bfda90
Note: storage-class is partiton-silver

**Comment by majst01** [comment]
Seems to be a issue based on your rights, will all rights i get:
```json
   "...",
    "ProjectID": "39fe6144-d0d1-4cd2-a2a4-831672257ae7",
    "ProtectionState": "FullyProtected",
    "ReplicaCount": 2,
    "Size": 2147483648,
    "State": "Available",
    "Statistics": {
        "CompressionRatio": 0.04077325097705375,
        "LogicalUsedStorage": 105852928,
        "PhysicalUsedStorage": 4315968
    },
    "StorageClass": "partition-silver",
    "...",
 ```

Will keep you updated

**Comment by majst01** [comment]
> Seems to be a issue based on your rights, will all rights i get:
> 
> ```json
>    "...",
>     "ProjectID": "39fe6144-d0d1-4cd2-a2a4-831672257ae7",
>     "ProtectionState": "FullyProtected",
>     "ReplicaCount": 2,
>     "Size": 2147483648,
>     "State": "Available",
>     "Statistics": {
>         "CompressionRatio": 0.04077325097705375,
>         "LogicalUsedStorage": 105852928,
>         "PhysicalUsedStorage": 4315968
>     },
>     "StorageClass": "partition-silver",
>     "...",
> ```
> 
> Will keep you updated

OK, access to CompressionRatio and LogicalUsedStorage is only provided for Users with highest privileges, e.g. only Storage Admins. Size and PhysicalStorageUsed is visible to end users. If this is not the case in your case, this must be an frontend issue.

So please ensure you have the latest version of `cloudctl` installed. You can always check with:

```bash
cloudctl update check
```
and update if required with:
```bash
cloudctl update do
```

**Comment by fireba11** [comment]
got the latest version :-)

**Comment by majst01** [comment]
But according to your json output above, size is shown !

**Comment by majst01** [comment]
Fix was on the wrong side, must be fixed on server side.

**Comment by majst01** [comment]
new cloud-api with a fix is deployed, please recheck and close if possible

**Comment by fireba11** [comment]
okay, now i get
    "ProjectID": "39fe6144-d0d1-4cd2-a2a4-831672257ae7",
    "ProtectionState": "FullyProtected",
    "ReplicaCount": 2,
    "Size": 322122547200,
    "State": "Available",
    "Statistics": {
        "CompressionRatio": 0,
        "LogicalUsedStorage": 314095771648,
        "PhysicalUsedStorage": 0
    },
    so i see logical instead of physical and get a used value that seems correct with
    cloudctl volume ls
    so i guess it's working as inteded now? :-)

**Comment by majst01** [comment]
please close this issue if you don't mind
