### ISSUE TITLE
[completion]

### ISSUE THREAD

**Issue by TLINDEN** [fi-ts/cloudctl#179]
Howdy,

after installing cloudctl according to the onboarding guide, including bash completion config, completion for other things is not working anymore. As far I can see, file/dir name completion seems to be affected. Examples are:
```
chmod 700 <tab>
tar xvfz <tab>
git add <tab>
```

The completion config looks as follows:
```
source /usr/share/bash-completion/bash_completion
source <(cloudctl completion bash)
alias c=cloudctl
complete -F __start_cloudctl c
```

Completion for the `c` alias itself works as expected. Completion for commands where a file/directory is the 2nd parameter is also still working, such as `ls <tab>` or `rm <tab>`.

Versions:
Kubuntu (Ubuntu 21.04)
bash 5.1.4(1)
bash-completion 1:2.11-2ubuntu1

**Comment by Gerrit91** [comment]
Hi, interesting. Never seen this behavior before but I am also a zsh user. At which point in time does it break for you? After `complete -F __start_cloudctl c`?

**Comment by TLINDEN** [comment]
Oops! Your assumption is correct, it happens **before** that, but right after `source /usr/share/bash-completion/bash_completion`. So bash-completion itself is broken on my system somehow.

Thanks for the pointer!

**Comment by TLINDEN** [comment]
PS: interesting. If I change this command to:
```
. /usr/share/bash-completion/bash_completion
```

completion works as expected :) So, `.` and `source` seem to behave differently.

**Comment by TLINDEN** [comment]
PS: ok, the error was to use `source` instead of `.`, they seem to behave differently.

**Comment by Gerrit91** [comment]
Mh. Sounds odd, I thought `source` and `.` are the exact same thing. Please re-open if you experience problems like this again and we can try to investigate further.
