### ISSUE TITLE
postgres: `cloudctl postgres ls` should show if a postgres is primary or standby

### ISSUE THREAD

**Issue by FrankEppink** [fi-ts/cloudctl#194]
postgres: `cloudctl postgres ls` should show if a postgres is primary or standby

this would be really helpful as the approach to check for 

```
connection:
    localsideisprimary: false
```
or
```
connection:
    localsideisprimary: true
```

via `cloudctl postgres describe <id> -o yaml` only seems to work with extended rights

**Comment by eberlep** [comment]
`cloudctl postgres describe -o wide` does show this already, albeit somewhat cramped.

I think something like `cloudctl postgres describe -o replication` would be more useful.

**Comment by FrankEppink** [comment]
Using the `-o wide` option with the `cloudctl postgres ls` is what I was looking for, I did not know that option:

`cloudctl postgres ls -o wide`

closing this issue.
