### ISSUE TITLE
--kubeconfig Flag Does Not Work

### ISSUE THREAD

**Issue by eberlep** [fi-ts/cloudctl#195]
The `--kubeconfig` flags does not seem to work.

I usually set the `KUBECONFIG` variable per terminal to work with different K8s clusters at the same time. As the `cloudctl` binary uses the kubernetes config file to store it's credentials, I cannot use `cloudctl` in such terminals without logging in again or pointing it to another kubeconfig.

It works if I set the `KUBECONFIG` variable just for my `cloudctl` call (via `alias c='KUBECONFIG="$HOME/.kube/config" cloudctl'`), but not via the `--kubeconfig` command line flag.

**Comment by Gerrit91** [comment]
There's even more to that and it's equivalent to metalctl, flags like `--url`, `--hmac` and `--apitoken` also do not work anymore via command line argument. 

After short inspection I found out that these flags are empty during the init phase of the command tree, they will then be available within the actual cobra command funcs. Hence, I am assuming it was introduced through https://github.com/fi-ts/cloudctl/pull/111. I guess we could fix it by moving client initialization into a `PersistentPreRun` function of the root command.

**Comment by Gerrit91** [comment]
Turns out it's not so easy to fix with the current command tree initialization approach. I fixed the issue in my latest metalctl branch now, but it's not so nicest thing. Not our fault though, it's a cobra / viper design thing that requires this. :worried: 

Maybe someone has another idea?
