### ISSUE TITLE
Receive error message on cloudctl cluster create

### ISSUE THREAD

**Issue by michaelottofits** [fi-ts/cloudctl#20]
Receive error message on cloudctl cluster create
Message: 
**"Error: An unexpected error has occurred: Put "https://*****cloud/v1/cluster": context deadline exceeded"**

But cluster is created.

cloudctl version v0.8.3 (f395743f), tags/v0.8.3-0-gf395743, 2020-09-25T12:30:30Z
OS:
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

**Comment by Gerrit91** [comment]
Thanks for reporting. 

This is most certainly not a cloudctl issue. Seems like the cluster creation hangs when reporting the cluster to the accounting-api. The accounting-db will be moved to SSD storage soon, which should mitigate this issue. We are also planning to make these kind of requests to the accounting-api asynchronously. Opened an issue for that in the cloud-api project.
