### ISSUE TITLE
Add configuration for Pod Security Standards

### ISSUE THREAD

**Issue by Gerrit91** [fi-ts/cloudctl#234]
This allows a user to configure the `PodSecurity` admission plugin with defaults and exemptions. 

This is supported by Gardener: https://gardener.cloud/docs/gardener/usage/pod-security/. We can also see that disabling the `PodSecurityPolicies` is required by Gardener before upgrading the shoot Kubernetes version.

As a proposal, the `cluster update` command could take some more flags:

```bash
cloudctl cluster update <id> --disable-pod-security-policies --enable-pod-security \
--ps-enforce="privileged" \
--ps-enforce-version="latest" \
--ps-audit="privileged" \
--ps-audit-version="latest" \
--ps-warn="privileged" \
--ps-warn-version="latest" \
--ps-usernames-exemptions="user-a" \
--ps-runtime-classes-exemptions="runtime" \
--ps-namespaces-exemptions="kube-system,metallb-system" 
```

In the cloud-api, we should prevent a user from updating to Kubernetes v1.25 when `allowPrivileged` is enabled on the shoot and `PodSecurityPolicy` is not explicitly disabled.

**Comment by mwennrich** [comment]
Seems a bit too much to me. I don't see any use for `username-exemptions` or `runtime-classes-exemptions`.
And `namespaces-exemptions` can simply be handled by appropriately labeling the namespaces.
The same for versions ... users can always pin to a version other than `latest` with namespace labels if needed.

I would go for something simple like `--default-pod-security-standard="privileged|baseline|restricted"`, which only sets `enforce`.
And everything else should be handled by the users in their deployments with appropriate namespace labels (like before with psp-rbacs). 

The default for `cluster create` should probably be `restricted`, which corresponds best to the current state where PSP are enabled by default.

And cloud-api must always add exemptions for the `kube-system` and `csi-lvm` namespaces.

**Comment by majst01** [comment]
> Seems a bit too much to me. I don't see any use for `username-exemptions` or `runtime-classes-exemptions`. And `namespaces-exemptions` can simply be handled by appropriately labeling the namespaces. The same for versions ... users can always pin to a version other than `latest` with namespace labels if needed.
> 
> I would go for something simple like `--default-pod-security-standard="privileged|baseline|restricted"`, which only sets `enforce`. And everything else should be handled by the users in their deployments with appropriate namespace labels (like before with psp-rbacs).
> 
> The default for `cluster create` should probably be `restricted`, which corresponds best to the current state where PSP are enabled by default.
> 
> And cloud-api must always add exemptions for the `kube-system` and `csi-lvm` namespaces.

I tend to agree here, i would not give users so much possibilities as proposed by @Gerrit91. Defining PodSecurity by namespaces is perfectly fine.

**Comment by Gerrit91** [comment]
I like the idea of the default of `--default-pod-security-standard=` and then let people fine tune through namespace labels. :+1:

Only thing that was important to me is that there are not only namespace labels, which can quickly lead to people neglecting the pod security. 

Still not sure if I would allow disabling the admission plugin for people that do not want to use it.

**Comment by Gerrit91** [comment]
Unfortunately, disabling the PSP plugin seems not to work before Gardener v1.58:

```
❯ c cluster update 0e7658de-aaeb-4fcf-a511-7bea6e4e2831 --disable-pod-security-policies --yes-i-really-mean-it
Error: [POST /v1/cluster][500] updateCluster default  Shoot.core.gardener.cloud "inttest10" is invalid: spec.kubernetes.kubeAPIServer.admissionPlugins[1]: Forbidden: admission plugin "PodSecurityPolicy" cannot be disabled (500)
```

So, for now we can only provide configuring the PSS admission plugin.

**Comment by Gerrit91** [comment]
I think this issue is implemented now, we also have some integration tests. However, Kubernetes 1.25 and disabling the PSPs will not come before g/g v1.58.
