### ISSUE TITLE
cloudctl update do is broken

### ISSUE THREAD

**Issue by fireba11** [fi-ts/cloudctl#298]
cloudctl update do
Error: Get "http://localhost:8080/cloud/v1/version": dial tcp 127.0.0.1:8080: connect: connection refused

That's not usefull :-P

Manually installing the latest version works of course, though that shows

cloudctl update check
checksum:56e809d92c962eaeb8f2267fd2ab956b
latest version:v0.12.17 from:2024-03-06T13:55:49Z
local  version:v0.12.18 from:2024-04-23T08:52:15Z
cloudctl is up to date

which is a little irritiating :-P

**Comment by majst01** [comment]
You updated to a newer version than strictly required, which should be no problem.

The error you get is irritating ? do you go through a proxy ?

**Comment by fireba11** [comment]
Not sure if my Ticket was quite clear.
Point 1:
cloudctl update do
doesn't work, i get an error with it trying to connect to local host which makes no sense. curl etc. can download things without issue and it worked with older versions fine.

Point 2:
update check reports the latest version *higher* that mine. it doesn't say *required* version is lower :-D

**Comment by majst01** [comment]
Please run:

```
DEBUG=1 cloudctl update do
```

and remove potential authorization headers from your output. Still confused why your cloudctl will connect to localhost.

what does your `~/.cloudctl/config.yaml` look like ?

**Comment by fireba11** [comment]
Ah. My user doesn't have permissions to write in /usr/local/bin/ so i was running it with sudo. Apparently it doesn't use my ~/.cloudctl/config.yaml then any more and failes with that strange error.
Worked at some point ;-)

**Comment by majst01** [comment]
OK, so please close this issue if you feel confident

**Comment by fireba11** [comment]
thx
