### ISSUE TITLE
show details for cluster inputs

### ISSUE THREAD

**Issue by fireba11** [fi-ts/cloudctl#305]
Is there a way to show details for cluster inputs? Some (like machinetypes, firewalltypes and possibly seeds) would warrant some details.
Or are they documented somewhere i did ont look?

**Comment by majst01** [comment]
What exactly are u missing ? The relevant documentation can be found in the official end user documentation of the FCN Product at https://status.fits.cloud/ if you follow the "Documentation" link on the upper right corner.

**Comment by majst01** [comment]
> @majst01 cores/ram/ssd size for the different node types is not mentioned anywhere ;-)

Is part of the customer contract documentation
