### ISSUE TITLE
Q: can cluster update skip versions

### ISSUE THREAD

**Issue by fireba11** [fi-ts/cloudctl#316]
I've looked at the documentation but i can't tell if i can use cluster update to upgrade several versions at once or if i need to upgrade to every minor version.
e.g. can i do
1.26 -> 1.28
or do i need to go
1.26 -> 1.27 -> 1.28

**Comment by majst01** [comment]
It is not possible to skip Minor Versions, so the second approach is required

**Comment by fireba11** [comment]
@majst01 thank you for the prompt answer :-)
