### ISSUE TITLE
s3 create --max-buckets 0 does not work

### ISSUE THREAD

**Issue by Pilzington** [fi-ts/cloudctl#323]
When creating a s3 user setting `--max-buckets 0` defaults to `1000`.
```bash
$ cloudctl s3 create --project ... --partition nbg-w8101 --id zerobuckets --max-buckets 0
endpoint: https://s3.prod-03-nbg-w8101.fits.cloud
id: zerobuckets
keys:
    - accesskey: ...
      secretkey: ...
maxbuckets: 1000
name: ..._zerobuckets
partition: nbg-w8101
project: ...
tenant: ...
```
A user with zero buckets would be nice to control the access to s3 for certain applications.

**Comment by majst01** [comment]
i do not understand the purpose of a s3 endpoint which does not allow create buckets ?

**Comment by Pilzington** [comment]
For example, you have a bucket admin, who creates all buckets and gives access to others users. These users are only allowed to use the provided buckets. They are not allowed to create their own buckets.

**Comment by Pilzington** [comment]
With #324 there is no real need for this.
