### ISSUE TITLE
Use actual binary name to generate bash "completion" output

### ISSUE THREAD

**Issue by mweisbach** [fi-ts/cloudctl#6]
Hi,

I would like to propose to generate (bash) completion output based on commands actual name. This would allow us to (re)name "cloudctl" to any other name, e.g. "something-else-than-cloudctl", "metal-stack-ctl" or "cloudctl-vX.Y.Z", on a local host.

In case of the binary was renamed to "something-else-than-cloudctl" the output of "./something-else-than-cloudctl completion" still refers to original (fixed/static) "cloudctl" command name and therefore th output of "completion" option can't be used to get bash completion working for "something-else-than-cloudctl" command without further modifications.

-- Michael

**Comment by majst01** [comment]
What is the rational behind renaming a binary, tbh this does not work in your proposed way for other binaries as well. It works OTOH if you create a alias like must of us do:

```bash
alias m='metalctl'
alias c='cloudctl'
```
then the real binary is called.

**Comment by mweisbach** [comment]
Hi majst01, I'm familiar with aliasing :-). In my case, the request was made because there is another team which also selected "cloudctl" as their deliverable name (and I proposed to select a more specific name to them as well). As long as you do not plan to "control everything" of the entire "Cloud world", it would be good to allow a different name and not just tweak it via an alias.

**Comment by majst01** [comment]
As i said, because other binaries do not support such a "feature" i am not keen to do so here as well.

**Comment by mweisbach** [comment]
So, let's close this issue then.

**Comment by majst01** [comment]
You can also do:

```bash
source <(cloudctl completion | sed s/cloudctl/c/g)
```

replace cloudctl which whatever you have named your binary
