### ISSUE TITLE
Helptext for "cloudctl completion zsh" is wrong

### ISSUE THREAD

**Issue by vmsimon** [fi-ts/cloudctl#62]
`cloudctl completion zsh --help`

gives
`...
echo -e '#compdef _cloudctl cloudctl\n. <(cloudctl zsh-completion)' > $ZSH/completions/_cloudctl
...`

has to change to
`...
echo -e '#compdef _cloudctl cloudctl\n. <(cloudctl completion zsh)' > $ZSH/completions/_cloudctl
...`

**Comment by majst01** [comment]
@vmsimon thanks for the report, will be fixed in the next release with #63
