### ISSUE TITLE
Error on get version of cloudctl

### ISSUE THREAD

**Issue by michaelottofits** [fi-ts/cloudctl#83]
There is an error in the display of the version.

on last version i get follow message:

```
client: v0.9.8 (88aa93c8), tags/v0.9.8-0-g88aa93c, 2021-06-24T06:09:36Z, go1.16.5
Error: failed to get server info: response status code does not match any response statuses defined for this endpoint in the swagger spec (status 403): {}
```

**Comment by majst01** [comment]
Still there ?  Please check
This was yesterday during cloud-api outage for about 45min.

**Comment by michaelottofits** [comment]
the error probably occurred because of missing login at the oidc provider
