### ISSUE TITLE
Add missing parameter <clusterid> in "cluster machine ls" help text

### ISSUE THREAD

**Issue by tjuerge** [fi-ts/cloudctl#92]
In current client version v0.9.10 there's the required clusterid parameter missing in the command's help text:
![image](https://user-images.githubusercontent.com/2626998/129615833-5eeb8a52-5776-4a7a-819b-bffb4d375451.png)

**Comment by tjuerge** [comment]
Same with "cluster logs":
![image](https://user-images.githubusercontent.com/2626998/129616851-315c1bc3-3d64-4f5e-822f-806fa9d6a097.png)

**Comment by majst01** [comment]
Hi @tjuerge 
thanks for reporting !
